### ISSUE TITLE
Spec Status?

### ISSUE THREAD

**Issue by dret** [Maps4HTML/HTML-Map-Element#7]
i am wondering if https://github.com/dret/HTML5-overview might be a good place to include this element, or whether this may be a bit too early. the page above mostly focuses on official W3C specs, but also has a couple of other documents. but i think these are at least all driven by some sort of community. would that apply to this spec? if not yet, are there plans to go this route?

**Comment by prushforth** [comment]
dret:  I think it is too early.  There are many areas that are not solid yet, not least of which is that there is only one implementation.  But that is definitely the direction we're going in.  We are using the W3C community group resources to organize the discussion between map enthusiasts.  Once we have a more vibrant community, we can then start discussions with the HTML web apps community.  At least that's kind of the way I was seeing things go.  

I wrote up a ["use cases and requirements" document](http://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/), from which I am slowly generating the spec for the HTML-Map-Element in this repo.  I intend to only add spec as the implementation proceeds in the https://github.com/Maps4HTML/Map-Custom-Element repo.  Hopefully that clarifies things.  Feel free to submit issues, as you've done, I am happy for any and all feedback.

Cheers,
Peter

**Comment by dret** [comment]
On 2015-10-23 11:00, Peter Rushforth wrote:
> dret: I think it is too early. There are many areas that are not solid
> yet, not least of which is that there is only one implementation. But
> that is definitely the direction we're going in. We are using the W3C
> community group resources to organize the discussion between map
> enthusiasts. Once we have a more vibrant community, we can then start
> discussions with the HTML web apps community. At least that's kind of
> the way I was seeing things go.

sounds good. afaict, it's usually better to try to engage people earlier 
on, instead of presenting them with something and assuming they're just 
going to accept it. and one implementation already is something, and 
maybe good enough as a starting point.

> I wrote up a "use cases and requirements" document
> <http://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/>,
> from which I am slowly generating the spec for the HTML-Map-Element in
> this repo. I intend to only add spec as the implementation proceeds in
> the https://github.com/Maps4HTML/Map-Custom-Element repo. Hopefully that
> clarifies things. Feel free to submit issues, as you've done, I am happy
> for any and all feedback.

thanks for the pointer. this is very premature, but should you be at 
www2016, we would be more than happy to try to have a little "HTML map 
element" hackathon at locweb2016, or something along those lines. 
www2016 in general would be good to work on exposure in the w3c 
community. thanks for your feedback, i am going to close this issue for now.

**Comment by prushforth** [comment]
Hi Erik,

Thanks for the advice regarding engagement. I have posted to the Web Incubator Community Group / Specifiction, here https://discourse.wicg.io/t/use-cases-and-requirements-for-standardizing-web-maps/1161/1 .  I'm sure it will need lots time and effort for the relevant communities to warm up to the idea, but if we don't try, it won't happen, right?  Anyway good point to let them know what's happening over here.

I don't really have a strategy regarding exposure, but I am planning on going to www2016, and would love to get a hackathon going.   I am planning to do a poster session there, as the formal paper tracks did not seem to favour this topic.  Feel free to contact me if you want some help to organize a hackathon / MapML event.
