### ISSUE TITLE
Rename the <map> type extension custom element to <web-map> custom element

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/HTML-Map-Element#8]
[The comment was made in the WICG](https://discourse.wicg.io/t/use-cases-and-requirements-for-standardizing-web-maps/1161/6?u=peterr) that the <map> element *name* might conflict with existing implementation / content meant for the `<MAP>` (i.e. the original html 2 semantic) element.  "map" is appropriate from a [HTML author perspective](https://tools.ietf.org/html/draft-nottingham-for-the-users-00#section-3), [I think, despite the existing usage](https://www.google.ca/search?q=map) - see the WICG discussion for the etymology of the `<MAP>` element. 

 TBD is whether a today's browser implementation could be convinced to work with a future `<map>` element, by providing "fallback" content per today's HTML specification, and tomorrow's browser could provide the enhanced behaviour providing it can detect "tomorrow's" HTML semantics.

**Comment by dret** [comment]
i am not sure that <MAP> and concept proposed here have much, if anything, in common. <MAP> is literally just a map of clickable regions overlayed on an image. it has nothing to do with interactions that affect the image in any way.

**Comment by prushforth** [comment]
Hi Erik, I see your point!  I have quite a bit of code and documentation that describes the `<map>` type extension element at this moment.  Type extension custom elements do a nice job of hijacking the behaviour of native elements, and the Polymer project devs are keen to see people implementing custom behaviours for existing HTML vocabulary elements.  Since the word "map" to me, and to the cartographic community (I presume!), has the geographic meaning, I thought it would be an easy sell to the end users as "map".  So that's why I chose the type-extension route.  If and when it comes to native implementation, I personally do not care what it is called, as long as it is well implemented and marketed.

Also, if you could join the  Maps4HTML community group that would be great, as well as allowing us to freely share pull requests and ideas, for example.

Thank you!

**Comment by dret** [comment]
On 2015-10-29 16:53, Peter Rushforth wrote:
> Also, if you could join the Maps4HTML community group that would be
> great, as well as allowing us to freely share pull requests and ideas,
> for example.

done!

**Comment by prushforth** [comment]
Awesome, thanks!

**Comment by prushforth** [comment]
Renamed the [prototype](http://maps4html.github.io/Web-Map-Custom-Element/) map to [web-map](http://maps4html.github.io/HTML-Map-Element/spec/), per suggestion by Nelson on [discourse](https://discourse.wicg.io/t/use-cases-and-requirements-for-standardizing-web-maps/1161/5).  @dret @nelsonmenezes
